services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: withdrawal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: withdrawal_system
      MYSQL_USER: withdrawal_user
      MYSQL_PASSWORD: withdrawal_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    restart: unless-stopped
    networks:
      - withdrawal-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # LocalStack for AWS services emulation
  localstack:
    image: localstack/localstack:latest
    container_name: withdrawal-localstack
    environment:
      - SERVICES=sqs,secretsmanager
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh
    networks:
      - withdrawal-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # API Server
  api-server:
    container_name: withdrawal-api-server
    depends_on:
      mysql:
        condition: service_healthy
      localstack:
        condition: service_healthy
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/dockerfile.packages
      target: api-server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=withdrawal_system
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
    networks:
      - withdrawal-network
    # volumes:
    #   - ../prisma:/app/prisma:ro
    #   - ../apps:/app/apps:ro
    #   - ../packages:/app/packages:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  withdrawal-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
