version: '3.8'

services:
  # helloworld application service
  helloworld:
    build:
      context: ..
      dockerfile: docker/dockerfile.packages
      target: helloworld
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # Development environment service (auto-restart on source code changes)
  helloworld-dev:
    build:
      context: ..
      dockerfile: docker/dockerfile.packages
      target: builder
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ..:/app
      - /app/node_modules
    command: yarn nx serve helloworld
    profiles:
      - dev
    networks:
      - app-network

  # Future API service example
  # api:
  #   build:
  #     context: ..
  #     dockerfile: docker/dockerfile.packages
  #     target: api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: