version: '3.8'

services:
  # MySQL Database only for development
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-pass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-withdrawal_system}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    restart: unless-stopped

volumes:
  mysql_data: