services:
  # Helloworld application service
  helloworld:
    build:
      context: ..
      dockerfile: docker/dockerfile.packages
      target: helloworld
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - mustb-asset-withdrawal

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: withdrawal_system
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mustb-asset-withdrawal

  # API Server
  api-server:
    depends_on:
      - mysql
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/dockerfile.api-server
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=withdrawal_system
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
    networks:
      - mustb-asset-withdrawal

networks:
  mustb-asset-withdrawal:
    driver: bridge

volumes:
  mysql_data:
