version: '3.8'

services:
  # helloworld application service
  helloworld:
    build:
      context: ..
      dockerfile: docker/dockerfile.packages
      target: helloworld
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - mustb-asset-withdrawal

  # Future API service example
  # api:
  #   build:
  #     context: ..
  #     dockerfile: docker/dockerfile.packages
  #     target: api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped
  #   networks:
  #     - mustb-asset-withdrawal

networks:
  mustb-asset-withdrawal:
    driver: bridge
