version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: withdrawal-localstack
    environment:
      - SERVICES=sqs,secretsmanager
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh
    networks:
      - withdrawal-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  withdrawal-network:
    external: true
    name: docker_withdrawal-network