# Production Release Workflow
# This workflow is currently disabled and for reference only
# To enable: uncomment the 'on' section and configure secrets

name: Production Release

# DISABLED - Uncomment to enable
# on:
#   release:
#     types: [published]

# DISABLED - This job will not run
jobs:
  build-push:
    runs-on: ubuntu-latest
    # DISABLED - This job is currently disabled
    if: false # This prevents the job from running

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image (production & version)
        run: |
          VERSION=${GITHUB_REF##*/}
          docker build -f docker/dockerfile.packages -t ${{ secrets.ECR_REPO }}:production -t ${{ secrets.ECR_REPO }}:$VERSION .
          docker push ${{ secrets.ECR_REPO }}:production
          docker push ${{ secrets.ECR_REPO }}:$VERSION

# Required secrets:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - ECR_REPO (format: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/your-repo)
